version: "3"
services:
  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: app_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api-gateway

  api-gateway:
    container_name: "api-gateway"
    build:
      dockerfile: Dockerfile
      context: ./gateway
    ports:
      - 4000:8000
    depends_on:
      - mysql
